# Generated by Django 2.2.8 on 2020-01-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalconfig',
            name='icon',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
