# Generated by Django 2.2.8 on 2020-01-09 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_auto_20200109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalconfig',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_externalconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filterconfig',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_filterconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_reportconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_systemconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
