# Generated by Django 2.2.8 on 2020-01-09 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs', '0003_auto_20200109_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_externalconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filterconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_filterconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_reportconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_systemconfig_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('module', models.CharField(max_length=200, unique=True)),
                ('field', models.CharField(max_length=200, unique=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_fieldconfig_creator', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_fieldconfig_last_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
