# Generated by Django 2.2.8 on 2020-01-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_auto_20200109_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconfig',
            name='field',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fieldconfig',
            name='module',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='field',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='module',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
