# Generated by Django 2.2.8 on 2020-01-09 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_auto_20200109_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_externalconfig_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='externalconfig',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_externalconfig_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='externalconfig',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='externalconfig',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on'),
        ),
        migrations.AlterField(
            model_name='fieldconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_fieldconfig_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='fieldconfig',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_fieldconfig_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='fieldconfig',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='fieldconfig',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on'),
        ),
        migrations.AlterField(
            model_name='filterconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_filterconfig_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='filterconfig',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_filterconfig_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='filterconfig',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='filterconfig',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on'),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_reportconfig_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_reportconfig_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_systemconfig_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs_systemconfig_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='time_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on'),
        ),
    ]
