# Generated by Django 2.2.8 on 2020-01-06 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('field_list', models.TextField(blank=True, null=True)),
                ('order_by', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.CharField(max_length=200)),
                ('private', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters_filter_creator', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters_filter_last_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=200, null=True)),
                ('operator', models.CharField(choices=[('exact', 'Exact'), ('iexact', 'Exact case-insensitive'), ('contains', 'Contains'), ('icontains', 'Contains case-insensitive'), ('in', 'In'), ('gt', 'Greater than'), ('gte', 'Greater than equal'), ('lt', 'Less than'), ('lte', 'Less than equal'), ('startswith', 'Start with'), ('istartswith', 'Start with case-insensitive'), ('endswith', 'End with'), ('iendswith', 'End with case-insensitive'), ('isnull', 'Is Null')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_details', to='filters.Filter')),
            ],
        ),
    ]
