# Generated by Django 2.2.8 on 2020-01-10 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_initial_db'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dob',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook_uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook UID'),
        ),
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts_contact_job', to='choices.ChoiceDetail', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name of contact'),
        ),
    ]
