# Generated by Django 2.2.8 on 2020-01-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_initial_db'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts_contact_city', to='choices.ChoiceDetail', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook url'),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts_contact_rate', to='choices.ChoiceDetail', verbose_name='Rate'),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts_contact_source', to='choices.ChoiceDetail', verbose_name='Source'),
        ),
    ]
