# Generated by Django 2.2.8 on 2020-01-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200110_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name of contact'),
        ),
    ]
