# Generated by Django 2.2.8 on 2020-01-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynafield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('ForeignKey', 'ForeignKey'), ('ManyToManyField', 'ManyToManyField'), ('OneToOneField', 'OneToOneField'), ('CharField', 'CharField'), ('TextField', 'TextField'), ('BooleanField', 'BooleanField'), ('NullBooleanField', 'NullBooleanField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('TimeField', 'TimeField'), ('BigIntegerField', 'BigIntegerField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SmallIntegerField', 'SmallIntegerField'), ('DecimalField', 'DecimalField'), ('FloatField', 'FloatField'), ('FileField', 'FileField'), ('ImageField', 'ImageField')], max_length=150)),
                ('verbose_name', models.CharField(blank=True, max_length=250, null=True)),
                ('fkmodule', models.CharField(blank=True, max_length=200, null=True)),
                ('on_delete', models.CharField(blank=True, choices=[('CASCADE', 'CASCADE'), ('PROTECT', 'PROTECT'), ('SET_NULL', 'SET_NULL'), ('DO_NOTHING', 'DO_NOTHING')], max_length=50, null=True)),
                ('default', models.CharField(blank=True, max_length=200, null=True)),
                ('max_length', models.IntegerField(blank=True, default=50, null=True)),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_choices', to='choices.Choice')),
            ],
        ),
    ]
