# Generated by Django 2.2.8 on 2020-01-09 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0002_initial_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices_choice_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
