# Generated by Django 2.2.8 on 2020-01-10 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('time_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified on')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('position', models.SmallIntegerField(default=1)),
                ('width', models.SmallIntegerField(choices=[('6', 'Half'), ('12', 'Full')], default='12')),
                ('module', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
                ('dashboard', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('type', models.CharField(choices=[('column', 'Column Chart'), ('line', 'Line Chart'), ('column-line', 'Column Line Chart'), ('pie', 'Pie Chart'), ('radar', 'Radar Chart'), ('table', 'Table')], max_length=200)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tile_creator', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_tile_last_modified', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('formula', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_details', to='dashboard.Tile')),
            ],
        ),
    ]
