# Generated by Django 2.2.8 on 2020-01-06 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modified', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.CharField(blank=True, max_length=5000, null=True)),
                ('url', models.CharField(blank=True, max_length=550, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('flaticon2-gear', 'System'), ('flaticon2-user', 'Customer'), ('flaticon2-send', 'Email'), ('flaticon2-calendar-1', 'Event'), ('flaticon2-indent-dots', 'Task')], max_length=50, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_notice_creator', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices_notice_last_modified', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
